name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 12
        uses: actions/setup-java@v3
        with:
          java-version: '12'
          distribution: 'microsoft'
      - name: Build with Maven
        run: mvn package
